name: gpuenv
channels:
  - defaults
dependencies:
  - python=3.11.5
  - pip
  - pip:
    - imbalanced-learn==0.10.1
    - keras
    - keras-tuner
    - matplotlib
    - numpy  # Consider specifying a version  
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.1
    - pandas
    - scikit-learn==1.2.0
    - scipy
#    - tensorflow-gpu==2.11.0  # Replace with the correct compatible version
    - tensorflow-macos
    - tensorflow-metal
    - data-complexity
    - xgboost
    - prompt_toolkit
    - mlxtend
    - boruta
    - skrebate
